name: EDATECH CI
on:
  pull_request:
    brancehs:
      - feature/*

jobs:
  build:
    name: Build backend
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout directory
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
          architecture: x64
      - name: Check
        run: ls
      - name: Build with Gradle
        run: ./backend/gradlew build