name: EDATECH CI
on:
  pull_request:
    branches:
      - dev

jobs:
  buildBackend:
    name: Build backend
    if: startsWith(github.head_ref, 'feature/') == true
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout directory
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
          architecture: x64
      - name: Build with Gradle
        run: gradle build --info
  buildFrontend:
    name: Build frontend
    if: startsWith(github.head_ref, 'feature/') == true
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout directory
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install, build and test with NPM
        run: |
          cd frontend
          npm install
          npm run build
          npm test